name: autoaim
channels:
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - numpy
  - pandas
  - matplotlib
  - cython
  - pillow
  - pip
  - pip:
    - pyautogui
    - jupyter
    - mss
    - torch-summary
    - pyYAML
    - requests
    - scipy
    - tqdm
    - tensorboard
    - seaborn
    - albumentations
    - opencv-python
    - ipykernel
    - autopy
    - fiftyone
    - "git+https://github.com/bcperry/cocoapi_windows.git#subdirectory=PythonAPI"