name: autoaim
channels:
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - torchsummary
  - cudatoolkit=11.3
  - numpy
  - pandas
  - matplotlib
  - cython
  - python-mss
  - pillow
  - pip
  - pip:
    - pyautogui
    - torchsummary
    - pyYAML
    - requests
    - scipy
    - tqdm
    - tensorboard
    - seaborn
    - albumentations
    - opencv-python
    - "git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI"